const CARE_ASSIST=1;
const CARE_ALONE = 2;
const CARE_RECOVER = 3;

const COLLECT_BTN = 'COLLECT_BTN';
const FAVOUR_BTN = 'FAVOUR_BTN';

const RADIO_TEST = 'RADIO_TEST';
const RADIO_SURVEY = 'RADIO_SURVEY';

const GROUP_TYPE_SINGLE='single';
const GROUP_TYPE_MULTI='multi';

module.export={
  CARE_ASSIST,
  CARE_ALONE,
  CARE_RECOVER,
  COLLECT_BTN,
  FAVOUR_BTN,
  RADIO_TEST,
  RADIO_SURVEY,
  GROUP_TYPE_SINGLE,
  GROUP_TYPE_MULTI
}